-- BUSINESS QUESTION: Do male or female customers drive more revenue?
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- BUSINESS QUESTION: Are discounts attracting high-value buyers or just deal-seekers?
-- Q2. Which customers used a discount but still spent more than the average?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- BUSINESS QUESTION: Which products deliver the best customer satisfaction?
-- Q3. Top 5 products with highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- BUSINESS QUESTION: Does faster shipping correlate with higher spend?
-- Q4. Compare average purchase amount between Standard and Express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- BUSINESS QUESTION: Is the subscription programme worth investing in?
-- Q5. Do subscribed customers spend more than non-subscribers?
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- BUSINESS QUESTION: Which products are most frequently discounted?
-- Q6. Top 5 products by discount application rate
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- BUSINESS QUESTION: What does our customer loyalty base look like?
-- Q7. Segment customers into New, Returning, and Loyal by purchase history
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment;

-- BUSINESS QUESTION: What are the hero products driving sales in each category?
-- Q8. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT category, item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- BUSINESS QUESTION: Does repeat buying behaviour predict subscription likelihood?
-- Q9. Subscription rate among repeat buyers (more than 5 previous purchases)
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- BUSINESS QUESTION: Which age group contributes most to total revenue?
-- Q10. Revenue contribution by age group
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
